import { test, expect } from '@playwright/test';

test.describe('Minimum App E2E Flows', () => {

  test.beforeEach(async ({ page }) => {
    // Go to dashboard
    await page.goto('/dashboard');
  });

  test('should load dashboard and show feed', async ({ page }) => {
    // Check for key elements instead of title if title is dynamic/missing
    await expect(page.getByText('For you')).toBeVisible();
    await expect(page.getByText('Recommended topics')).toBeVisible();
  });

  test('should create a new post', async ({ page }) => {
    await page.goto('/post/new');
    
    const title = `Test Post ${Date.now()}`;
    const content = 'This is a test content automatically generated by Playwright.';
    
    await page.getByPlaceholder('Title').fill(title);
    await page.getByPlaceholder('Tell your story...').fill(content);
    
    await page.getByRole('button', { name: 'Publish' }).click();
    
    await expect(page).toHaveURL(/\/dashboard/);
    await expect(page.getByText(title)).toBeVisible();
  });

  test('should filter posts by tag', async ({ page }) => {
    await page.goto('/dashboard');
    // Wait for page to load
    await page.waitForLoadState('networkidle');
    
    // Target the RIGHT sidebar specifically (second aside element)
    const rightSidebar = page.locator('aside').nth(1);
    const techLink = rightSidebar.locator('a[href="/dashboard/topic/programming"]');
    
    await techLink.click();
    await expect(page).toHaveURL(/\/dashboard\/topic\/programming/);
  });

  test('should view user profile', async ({ page }) => {
    // Create a post first to ensure we have an author
    await page.goto('/post/new');
    await page.getByPlaceholder('Title').fill('Profile Test Post');
    await page.getByPlaceholder('Tell your story...').fill('Content');
    await page.getByRole('button', { name: 'Publish' }).click();
    
    // Click author name. 
    // Gateway hardcodes ID ...001 which maps to "Alice Chen" in PostCard.
    // We look for "Alice Chen" specifically.
    await page.getByRole('link', { name: 'Alice Chen' }).first().click();
    
    await expect(page).toHaveURL(/\/user\//);
    await expect(page.getByText('Followers')).toBeVisible();
    await expect(page.getByText('Following')).toBeVisible();
  });
});
