import { test, expect } from '@playwright/test';

test.describe('Minimum App E2E Flows', () => {

  test.beforeEach(async ({ page }) => {
    // Go to dashboard (assumes no auth required for read or mock auth works)
    await page.goto('/dashboard');
  });

  test('should load dashboard and show feed', async ({ page }) => {
    await expect(page).toHaveTitle(/Minimum/);
    await expect(page.getByText('For you')).toBeVisible();
    await expect(page.getByText('Recommended topics')).toBeVisible();
  });

  test('should create a new post', async ({ page }) => {
    // Navigate to create post
    await page.goto('/post/new'); // Or click write button if visible
    
    // Fill form
    const title = `Test Post ${Date.now()}`;
    const content = 'This is a test content automatically generated by Playwright.';
    
    await page.getByPlaceholder('Title').fill(title);
    await page.getByPlaceholder('Tell your story...').fill(content);
    
    // Publish
    await page.getByRole('button', { name: 'Publish' }).click();
    
    // Verify redirect to dashboard
    await expect(page).toHaveURL(/\/dashboard/);
    
    // Verify post appears in feed
    await expect(page.getByText(title)).toBeVisible();
  });

  test('should filter posts by tag', async ({ page }) => {
    // Ensure we are on dashboard
    await page.goto('/dashboard');
    
    // Click a tag (e.g., Programming)
    const tag = 'Programming';
    await page.getByRole('button', { name: tag }).first().click();
    
    // Verify URL updates? Or just results. Current implementation updates URL?
    // Dashboard implementation used `fetch(url)` but does it update browser URL?
    // Let's check logic: NO, `dashboard/page.tsx` just updates state : `selectedTag`.
    // But wait, the button `onClick` sets state.
    
    // Verify results are filtered (check if non-matching posts are hidden? Hard to test without known data)
    // For now, check that the tag button behaves actively
    const tagBtn = page.getByRole('button', { name: tag }).first();
    await expect(tagBtn).toHaveClass(/bg-black/); // Active state
  });

  test('should view user profile', async ({ page }) => {
    // Click on a user name or avatar in the feed.
    // If feed is empty, this might fail unless we just created a post.
    
    // Create a post first to ensure there is an author to click
    await page.goto('/post/new');
    await page.getByPlaceholder('Title').fill('Profile Test Post');
    await page.getByPlaceholder('Tell your story...').fill('Content');
    await page.getByRole('button', { name: 'Publish' }).click();
    
    // Click author name
    // Found in PostCard ... need to know selector.
    // Dashboard renders PostCard.
    // Let's click the first "Demo User" or "User" text we see in the feed area.
    
    await page.locator('article').first().getByText(/User/i).first().click();
    
    // Verify profile page
    await expect(page).toHaveURL(/\/user\//);
    await expect(page.getByText('Followers')).toBeVisible();
    await expect(page.getByText('Following')).toBeVisible();
  });
});
